Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -24,13 +24,13 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
       
-      - name: Validate Docker Hub credentials
-        run: |
-          echo ${{ env.TEST }}          
-          if [ -z "${{ secrets.dockerhub.DOCKERHUB_USER }}" ] || [ -z "${{ secrets.dockerhub.DOCKERHUB_TOKEN }}" ]; then
-            echo "::error::Docker Hub credentials not set!"
-            exit 1
-          fi
+      # - name: Validate Docker Hub credentials
+      #   run: |
+      #     echo ${{ env.TEST }}          
+      #     if [ -z "${{ secrets.dockerhub.DOCKERHUB_USER }}" ] || [ -z "${{ secrets.dockerhub.DOCKERHUB_TOKEN }}" ]; then
+      #       echo "::error::Docker Hub credentials not set!"
+      #       exit 1
+      #     fi
       
       - name: Log in to Docker Hub        
         uses: docker/login-action@v3
